#!/bin/bash

if [ -f composer.lock ]
then
    CHANGED=`git diff $1 $2 --stat -- $GIT_DIR/../composer.lock | wc -l`
    if [ $CHANGED -gt 0 ];
    then
        echo "composer.lock has changed!"
        composer install --dev
    fi
    
    if [ ! -d vendor ]
    then
        composer install --dev
    fi
else
    echo "no composer.lock found!"
fi
