#!/bin/bash -eu
. "$GIT_COMMON_DIR/hooks/change_detector.sh"
. "$GIT_COMMON_DIR/hooks/php/composer/react.sh"

if [ -f composer.lock ]
then
	if has_changed post-checkout composer.lock
	then
		react
	fi
else
	echo "no composer.lock found!"
fi
