#!/bin/bash
. .git/hooks/php/composer/react.sh

if [ -f composer.lock ]
then
	CHANGED=$(git diff "$1" "$2" --stat -- "$GIT_DIR/../composer.lock" | wc --lines)
	if [ "$CHANGED" -gt 0 ];
	then
		react
	fi
else
	echo "no composer.lock found!"
fi
