#!/bin/bash
GIT_DIR=$(git rev-parse --git-dir)
. "$GIT_DIR/hooks/change_detector.sh"

if has_changed pre-commit composer.json
then
	composer validate
	isValid=$?
	if [ $isValid -ne 0 ]
	then
		exit $isValid
	fi
fi
