#!/bin/bash
GIT_COMMON_DIR=$(git rev-parse --git-common-dir)
. "$GIT_COMMON_DIR/hooks/change_detector.sh"

if has_changed pre-commit composer.json
then
	composer validate
	isValid=$?
	if [ $isValid -ne 0 ]
	then
		exit $isValid
	fi
fi
