#!/bin/bash
. .git/hooks/git_config_wrapper.sh
get_hook_required_config php-sismo path path
path_is_defined=$?
get_hook_required_config php-sismo slug slug
slug_is_defined=$?
if [ $path_is_defined -ne 0 -o $slug_is_defined -ne 0 ]
then
    exit 1
fi

php $path --quiet build $slug `git log -1 HEAD --pretty="%H"` &
