#!/bin/sh
if [ $php_sismo_slug == "putYourSismoProjectSlugHere" ]
then
    echo "Looks like you forgot to configure your sismo project slug"
    exit 2
fi

php $php_sismo_path --quiet build $php_sismo_slug `git log -1 HEAD --pretty="%H"` &
