#!/bin/bash -u
# The following condition won't work unless we use bash
# to understand this condition, see https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/Console/Command/ValidateSchemaCommand.php
app/console doctrine:schema:validate -q
RESULT=$?
if [ $[$RESULT & 2] == 2 ]
then
    echo "your schema is not up to date!"
    if [ -d "vendor/doctrine/migrations" ]
    then
	echo "Looks like you're using migrations"
	read -p "Do you wish to migrate ?" -n 1
	if [[ ! $REPLY =~ ^[OoYy]$ ]]
	then
	    echo "not updating"
	    exit 1
	fi
	app/console doctrine:migrations:migrate
    else
	echo "Looks like you're not using migrations! the following queries will be run:"
	app/console doctrine:schema:update --dump-sql --complete
	read -p "Do you wish to update the schema ?" -n 1
	if [[ ! $REPLY =~ ^[OoYy]$ ]]
	then
	    echo "not updating"
	    exit 1
	fi
	app/console doctrine:schema:update --force --complete
    fi
fi
