#!/bin/sh

phrases_file=.git/hooks/php/junkchecker/junk-phrases

if git-rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in `git diff-index --name-status $against -- | cut -c3-`; do
    for PHRASE in `cat $phrases_file`; do
        # Check if the file contains the phrase
        if [ "grep '$PHRASE' $FILE" ]
        then
            echo 'Junk phrase detected: '$FILE ' contains ' $PHRASE
            exit 1
        fi
    done
done
