#!/bin/sh

# Requires a patched ctags:
# https://github.com/shawncplus/phpcomplete.vim/wiki/Patched-ctags

set -e
trap "rm -f .git/tags.$$" EXIT
ctags \
    -Rf.git/tags.$$ \
    --fields=+aimS \
    --languages=php \
    --totals=yes \
    --tag-relative=yes \
    --PHP-kinds=cfiv \
    --exclude="app/cache/*" \
    --exclude="*.js" \
    --exclude=".svn" \
    --exclude=".git" \
    --exclude="vendor/*/vendor" \
    --exclude="vendor/*/Tests"


mv .git/tags.$$ .git/tags
