#!/bin/bash
GIT_COMMON_DIR=$(git rev-parse --git-common-dir)
. "$GIT_COMMON_DIR/hooks/change_detector.sh"

if has_changed pre-commit '**/*.php' '*.php'
then
	"$GIT_COMMON_DIR/hooks/php/cs-fixer/fix-cs"
fi
