#!/bin/bash
. "$GIT_DIR/hooks/change_detector.sh"

if has_changed pre-commit ./**/*.php ./*.php
then
	git diff-index --name-status 4b825dc642cb6eb9a060e54bf8d69288fbee4904 > /tmp/pwte
	.git/hooks/php/cs-fixer/fix-cs
fi
