#!/bin/bash
for enabled_plugin in `git config --get-all hooks.enabled-plugins`
do
    if [ -f .git/hooks/$enabled_plugin/post-commit ]
    then
        .git/hooks/$enabled_plugin/post-commit
    fi
done
