#!/bin/bash
if [ -f .git/hooks/hooksrc ]
then
    . .git/hooks/hooksrc
    for enabled_plugin in "${plugins[@]}"
    do
        if [ -f .git/hooks/php/$enabled_plugin/post-merge ]
        then
            .git/hooks/php/$enabled_plugin/post-merge $1
        fi
    done
fi
