#!/bin/sh
if [ -f .git/hooks/hooksrc ]
then
    . .git/hooks/hooksrc
    for enabled_plugin in $php_plugins
    do
        if [ -f .git/hooks/php/$enabled_plugin/post-merge ]
        then
            . .git/hooks/php/$enabled_plugin/post-merge
        fi
    done
fi
