#!/bin/bash
if [ -f .git/hooks/hooksrc ]
then
    . .git/hooks/hooksrc
    for enabled_plugin in "${plugins[@]}"
    do
        if [ -f .git/hooks/$enabled_plugin/post-checkout ]
        then
            .git/hooks/$enabled_plugin/post-checkout $1 $2
        fi
    done
fi
