#!/bin/sh
if [ -f .git/hooks/hooksrc ]
then
    . .git/hooks/hooksrc
    for enabled_plugin in $php_plugins
    do
        if [ -f .git/hooks/php/$enabled_plugin/pre-commit ]
        then
            . .git/hooks/php/$enabled_plugin/pre-commit
            if [ $? -ne 0 ]
            then
                exit 1
            fi
        fi
    done
fi

