#!/bin/sh

if git-rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in `git diff --cached --name-only` ; do
    # Check if the file contains junk
    grep -qE '^[ \t ]*xdebug_break()' $FILE
    if [[ $? -eq 0  ]]
    then
        echo $FILE ' contains xdebug_break()! To commit retry with --no-verify'
        exit 1
    fi
done
exit
