#!/bin/bash

set -e
trap "rm -f .git/tags.$$" EXIT
ctags \
	-h ".php" \
	-Rf.git/tags.$$ \
	--totals=yes \
	--tag-relative=yes \
	--PHP-kinds=cfiv \
	--regex-PHP='/(abstract)?\s+class\s+([^ ]+)/\2/c/' \
	--regex-PHP='/interface\s+([^ ]+)/\1/i/' \
	--exclude="app/cache/*" \
	--exclude="*.js" \
	--exclude=".svn" \
	--exclude=".git" \
	--exclude="vendor/*/vendor" \
	--exclude="vendor/*/Tests"

mv .git/tags.$$ .git/tags
