#!/bin/bash -eux

new_flags_are_supported()
{
	ctags --help|grep ' fields'|cut -d '"' -f2|grep a|grep i|grep m|grep S
}

build_ctags_command()
{
	local command=$(cat <<-EOT
		ctags
			-h ".php"
			-Rf.git/tags.$$
			--languages=php
			--totals=yes
			--tag-relative=yes
			--PHP-kinds=cfiv
			--exclude="*.js"
			--exclude=".svn"
			--exclude=".git"
			--exclude="vendor/*/vendor"
			--exclude="vendor/*/Tests"
		EOT
		)
	if [ new_flags_are_supported ]
	then
		command="${command} --fields=+aimS"
	else
		command="$command $(cat <<- OLD_FLAGS
			--regex-PHP='/(abstract)?\s+class\s+([^ ]+)/\2/c/'
			--regex-PHP='/interface\s+([^ ]+)/\1/i/'
			OLD_FLAGS
			)"
	fi
	local projectType
	if [ get_hook_config php-ctags project-type projectType ]
	then
		case projectType in
			symfony2)
				--exclude="app/cache/*"
			;;
			symfony1)
				--exclude="cache/*"
			;;
			*)
				echo "Unsupported project type $projectType" >&2
			;;
		esac
	fi
	eval $command
}

trap "rm -f .git/tags.$$" EXIT
build_ctags_command

mv .git/tags.$$ .git/tags
