#!/bin/bash
. $GIT_COMMON_DIR/hooks/git_config_wrapper.sh
get_hook_config php-sismo path path required
path_is_defined=$?
get_hook_config php-sismo slug slug required
slug_is_defined=$?
if [ $path_is_defined -ne 0 -o $slug_is_defined -ne 0 ]
then
	exit 1
fi

php "$path" --quiet build "$slug" "$(git log -1 HEAD --pretty="%H")" &
