#!/bin/bash -eu
GIT_DIR=$(git rev-parse --git-dir)
export GIT_DIR
test -d "$GIT_DIR"/rebase-merge -o -d "$GIT_DIR"/rebase-apply && exit 0
for enabled_plugin in $(git config --get-all hooks.enabled-plugins)
do
	if [ -f "$GIT_DIR/hooks/$enabled_plugin/post-checkout" ]
	then
		"$GIT_DIR/hooks/$enabled_plugin/post-checkout" "$1" "$2"
	fi
done
