#!/bin/bash -eu
GIT_COMMON_DIR=$(git rev-parse --git-common-dir)
export GIT_COMMON_DIR
test -d "$GIT_COMMON_DIR"/rebase-merge -o -d "$GIT_COMMON_DIR"/rebase-apply && exit 0
for enabled_plugin in $(git config --get-all hooks.enabled-plugins)
do
	if [ -f "$GIT_COMMON_DIR/hooks/$enabled_plugin/post-checkout" ]
	then
		"$GIT_COMMON_DIR/hooks/$enabled_plugin/post-checkout" "$1" "$2"
	fi
done
