#!/bin/bash
for enabled_plugin in $(git config --get-all hooks.enabled-plugins)
do
	if [ -f "$GIT_DIR/hooks/$enabled_plugin/post-merge" ]
	then
		"$GIT_DIR/hooks/$enabled_plugin/post-merge" "$1"
	fi
done
