#!/bin/bash
for enabled_plugin in $(git config --get-all hooks.enabled-plugins)
do
	if [ -f ".git/hooks/$enabled_plugin/pre-push" ]
	then
		".git/hooks/$enabled_plugin/pre-push"
		ret=$?
		if [ $ret -ne 0 ]
		then
			exit $ret
		fi
	fi
done
