#!/bin/bash
gitDir=$(git rev-parse --git-common-dir)
for enabled_plugin in $(git config --get-all hooks.enabled-plugins)
do
	if [ -f "$gitDir/hooks/$enabled_plugin/pre-push" ]
	then
		"$gitDir/hooks/$enabled_plugin/pre-push"
		ret=$?
		if [ $ret -ne 0 ]
		then
			exit $ret
		fi
	fi
done
