#!/bin/bash
GIT_COMMON_DIR=$(git rev-parse --git-common-dir)
. "$GIT_COMMON_DIR/hooks/git_config_wrapper.sh"
if git rev-parse --verify HEAD >/dev/null 2>&1; then
	against=HEAD
else
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in $(git diff-index --cached --name-status $against -- | cut -c 3-); do
	if [ -f "$FILE" ]
	then
		if [ -f "$GIT_COMMON_DIR/hooks/syntaxchecker/${FILE##*.}.sh" ]
		then
			source "$GIT_COMMON_DIR/hooks/syntaxchecker/${FILE##*.}.sh"
			if [ $? -ne 0 ]
			then
				echo 'Problem while parsing file ' "$FILE"
				exit 1
			fi
		fi
	fi
done
